spring.application.name=judwaa
spring.datasource.url=jdbc:h2:file:./../extras/backend/db_data/judwaa_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
vaadin.copilot.enable=false
app.fno.audio.enabled=false

# swagger.api.base-url=https://cuddly-chainsaw-g4rxwr7ww6wwc94xp-8080.app.github.dev/
swagger.api.base-url=http://localhost:8080

app.kotak.neo.enabled=true
app.kotak.neo.authorization=78220b50-9bf5-4180-8569-15110d00bec3
app.kotak.neo.mobile-number=+918310918712
app.kotak.neo.ucc=W7W6O
app.kotak.neo.mpin=383838
app.kotak.neo.login-url=https://mis.kotaksecurities.com/login/1.0
app.kotak.neo.session-file=../extras/backend/neo/kotak_session.json
app.kotak.neo.download-root=../extras/backend/neo/scripmaster_files
app.kotak.neo.file-paths-endpoint=/script-details/1.0/masterscrip/file-paths
# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=true
springdoc.show-actuator=true
springdoc.api-docs.enabled=true